# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpKfDPSOv_r2IzDLDqFkjisW6sCCble5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv("forestfires.csv")
df.head()

from google.colab import drive
drive.mount('/content/drive')

df.describe()

df.info()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

X = df.drop('area', axis=1)

Y = df.drop('area', axis=1)

X = df[['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain']]
y = df['area']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['month'] = label_encoder.fit_transform(df['month'])

df.drop(columns=["area"],inplace=True)

from sklearn.model_selection import train_test_split
x = df.drop(columns=["ISI"])
y = df["ISI"]

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['day'] = label_encoder.fit_transform(df['day'])

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['RH'] = label_encoder.fit_transform(df['RH'])

from sklearn.model_selection import train_test_split
x = df.drop(columns=["RH"])
y = df["RH"]

